[project]
name = "202606-playground"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "catboost>=1.2.10",
    "ipykernel>=7.2.0",
    "lightgbm>=4.6.0",
    "mypy>=2.1.0",
    "pandas>=3.0.3",
    "polars>=1.42.0",
    "ruff>=0.15.20",
    "seaborn>=0.13.2",
]

[tool.ruff]
line-length = 100

[tool.mypy]
ignore_missing_imports = true
